// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr1GDKwBcTV-j6b7rwqUWWhuLomqjOK8M',
    appId: '1:549720508674:web:63b74f08b21929d9aa5a1b',
    messagingSenderId: '549720508674',
    projectId: 'eass-using-rfid',
    authDomain: 'eass-using-rfid.firebaseapp.com',
    storageBucket: 'eass-using-rfid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmToqDj32lPLSXOFe5Cuntt6s1D2KsdeE',
    appId: '1:549720508674:android:d1f99b83580a75f9aa5a1b',
    messagingSenderId: '549720508674',
    projectId: 'eass-using-rfid',
    storageBucket: 'eass-using-rfid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDnGradDEOQtON2xfp4-1kXTrVH8iaiZQ',
    appId: '1:549720508674:ios:f2641043ce8bcfc4aa5a1b',
    messagingSenderId: '549720508674',
    projectId: 'eass-using-rfid',
    storageBucket: 'eass-using-rfid.appspot.com',
    iosBundleId: 'com.ecomile.eass',
  );
}
